params:
  epochs : 3
  batch_size : 32
  num_classes : 10
  input_shape : [28, 28]
  loss_function : sparse_categorical_crossentropy
  metrics : accuracy
  optimizer : SGD
  validation_datasize : 5000
  es_patience : 5

artifacts:
  artifacts_dir : artifacts
  model_dir : model
  plots_dir : plots
  model_name : model.h5
  plot_name : results_plot.png
  model_ckpt_dir : ModelCheckpoints
  callbacked_model_name : model_ckpt.h5

logs:
  logs_dir : logs_dir
  general_logs : general_logs
  tensorboard_root_log_dir : tensorboard_logs
